name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elasticsearch: ["8.4.3"]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Start Elasticsearch
      uses: ./elasticsearch
      with:
        security-enabled: false
        stack-version: ${{ matrix.elasticsearch }}
    - name: Elasticsearch is reachable
      run: |
        curl --verbose --show-error http://localhost:9200
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Download and preprocess data
      run: |
        python ir_exercise/preprocessor.py -d
    - name: Index data
      run: |
        python ir_exercise/indexer.py -r
